language: php
matrix:
  fast_finish: true
php:
- 7.1
cache:
  directories:
  - "$HOME/.composer/cache"
  - vendor
services:
- mysql
install:
- travis_retry composer self-update
- composer config -g github-oauth.github.com caf16441da5ba578b34a765e67e3bf2ad1941389
- travis_retry composer install --prefer-dist
before_script:
- travis_retry mysql -e 'CREATE DATABASE web;'
- php tests/_app/yii.php migrate --migrationPath=@zacksleo/yii2/oauth2/migrations --interactive=0
- ~/.composer/vendor/bin/codecept build
- php -S localhost:80 --docroot tests/_app/web &>/dev/null&
script:
- ~/.composer/vendor/bin/codecept run
