language: php
matrix:
  fast_finish: true
php:
- 7.1
cache:
  directories:
  - "$HOME/.composer/cache"
  - vendor
services:
- mysql
install:
- composer config -g github-oauth.github.com caf16441da5ba578b34a765e67e3bf2ad1941389
- travis_retry mysql -e 'CREATE DATABASE test;'
- travis_retry composer self-update
before_script:
- composer install --prefer-dist --dev --no-interaction
script:
- "./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover